### ISSUE TITLE
Deployment script generated seems to fail

### ISSUE THREAD

**Issue by hahmed** [projectkudu/KuduSync#30]
I have created a deployment script using 

````
azure site deploymentscript --aspNet5 project.json
````

For some reason when I deploy to azure, the deployment seems to fail via kudu sync.

It says there is an error at:
````
:: 1. Install KRE
call :ExecuteCmd PowerShell -NoProfile -NoLogo -ExecutionPolicy unrestricted -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = ''; [System.Threading.Thread]::CurrentThread.CurrentUICulture = '';& '%SCM_KVM_PS_PATH%' %*" install %SCM_KRE_VERSION% -%SCM_KRE_ARCH% -runtime %SCM_KRE_CLR% %SCM_KVM_INSTALL_OPTIONS%
IF !ERRORLEVEL! NEQ 0 goto error

IF EXIST "%USERPROFILE%\.k\temp-set-envvars.cmd" (
  CALL "%USERPROFILE%\.k\temp-set-envvars.cmd"
  DEL "%USERPROFILE%\.k\temp-set-envvars.cmd"
)
````
The **&** is the error at ````CurrentUICulture = '';& '%SCM_KVM_PS_PATH%' %*" ````

Can anyone help me out with this one?

Thanks

**Comment by ahmelsayed** [comment]
This is more of a KuduScript issue than KuduSync :) I know the names are confusing, but KuduScript is the one that generates the script you have above and KuduSync is just a copy tool that we use to copy files around.

With that said, this is happening because the azure cli is using an old version of KuduScript. `%SCM_KVM_PS_PATH%` was changed in beta4 to `%SCM_DNVM_PS_PATH%`. https://github.com/projectkudu/KuduScript/commit/20343271450e42400cebbfddedf47bee786e6ab6

if you can do the following 

```
npm install -g KuduScript
KuduScript -y --aspNet5 <path to project.json> --aspNet5Version <e.g: 1.0.0-beta7> --aspNet5Runtime <CLR|CoreCLR> --aspNet5Architecture <x86|x64>
```

**Comment by hahmed** [comment]
@ahmelsayed Thanks!

I will close this issue and open a new one in the correct repo (I never saw it) - having some other issues.
